require('configs.plugins')
require('configs.telescope')
require('configs.lspconfig')
require('configs.lualine')
require('configs.nvim-treesitter')
require('configs.options')
require('configs.theme')
-- require('configs.coq_nvim')
-- require('configs.nvim-compe')
require('configs.nvim-cmp')
require('configs.nvim-autopairs')
